### ISSUE TITLE
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get ytInitialData

### ISSUE THREAD

**Issue by androidplayer1** [TeamNewPipe/NewPipeExtractor#1025]
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get ytInitialData
at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getInitialData(YoutubeParsingHelper.java:530)
at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.extractClientVersionAndKeyFromHtmlSearchResultsPage(YoutubeParsingHelper.java:606)
at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getClientVersion(YoutubeParsingHelper.java:689)
at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.prepareDesktopJsonBuilder(YoutubeParsingHelper.java:1211)
at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.createDesktopPlayerBody(YoutubeParsingHelper.java:1337)
at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:841)
at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:60)

    implementation 'com.github.TeamNewPipe:NewPipeExtractor:2211a24b6934a8a8cdf5547ea1b52daa4cb5de6c'

Happens with every video

**Comment by FireMasterK** [comment]
That commit, is a few months old, have you tried updating the dependency version?

**Comment by AudricV** [comment]
@androidplayer1 Could you answer the question asked below, please? Thank you in advance.

**Comment by androidplayer1** [comment]
> @androidplayer1 Could you answer the question asked below, please? Thank you in advance.

worked fine on the last version state.
