### ISSUE TITLE
Caused by: java.lang.NoSuchMethodError: No static method encode(Ljava/lang/String;Ljava/nio/charset/Charset;)Ljava/lang/String; in class Ljava/net/URLEncoder

### ISSUE THREAD

**Issue by abutun** [TeamNewPipe/NewPipeExtractor#1209]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipeExtractor/releases/latest).
- [X] I am aware that this issue is being opened for the NewPipe Extractor, NOT the [app](https://github.com/TeamNewPipe/NewPipe), and my bug report will be dismissed otherwise.
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipeExtractor/issues) or [closed](https://github.com/TeamNewPipe/NewPipeExtractor/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.2

### Steps to reproduce the bug

![Image 003](https://github.com/user-attachments/assets/7ffa7646-b4e3-4855-8a8f-7bb841619b35)

```
compileOptions {
sourceCompatibility JavaVersion.VERSION_17
targetCompatibility JavaVersion.VERSION_17
}

gradle-8.5.1-bin

coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.0.4")

implementation 'com.github.teamnewpipe:NewPipeExtractor:0.24.2'
```

### Screenshots/Screen recordings

![Image 003](https://github.com/user-attachments/assets/7ffa7646-b4e3-4855-8a8f-7bb841619b35)

### Logs

`Caused by: java.lang.NoSuchMethodError: No static method encode(Ljava/lang/String;Ljava/nio/charset/Charset;)Ljava/lang/String; in class Ljava/net/URLEncoder; or its super classes (declaration of 'java.net.URLEncoder' appears in /system/framework/core-oj.jar) at org.schabi.newpipe.extractor.utils.Utils.encodeUrlUtf8(Utils.java:37) at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSuggestionExtractor.suggestionList(YoutubeSuggestionExtractor.java:56) at code.name.monkey.retromusic.stream.Extractor.suggestions$lambda$2(Extractor.kt:43) at code.name.monkey.retromusic.stream.Extractor.$r8$lambda$snA4ZM6MPxqwWF8AjNWwNzLwiJA(Unknown Source:0) at code.name.monkey.retromusic.stream.Extractor$$ExternalSyntheticLambda3.call(D8$$SyntheticClass:0) at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43) at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813) at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89) at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644) at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65) ![Image 003](https://github.com/user-attachments/assets/69b67e8e-bcc6-45c9-a8df-dbfe1f94952d) `

**Comment by abutun** [comment]
Thank you very much. That worked!
