### ISSUE TITLE
使用NewPipeExtractor  开发分支dev分支最新版下载youtube视频失败，报错Got error: "Sign in to confirm that you're not a bot"

### ISSUE THREAD

**Issue by evenly99** [TeamNewPipe/NewPipeExtractor#1216]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipeExtractor/releases/latest).
- [X] I am aware that this issue is being opened for the NewPipe Extractor, NOT the [app](https://github.com/TeamNewPipe/NewPipe), and my bug report will be dismissed otherwise.
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipeExtractor/issues) or [closed](https://github.com/TeamNewPipe/NewPipeExtractor/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.2

### Steps to reproduce the bug

使用NewPipeExtractor下载youtube视频，之前一直都是可以的。最近一直报 Got error: "Sign in to confirm that you're not a bot"。
我已经把NewPipeExtractor 更新到了最新版本

### Expected behavior

希望可以下载如 https://www.youtube.com/watch?v=q6Ni0_gBdOk 的youtube视频，这个视频用web打开是可以正常播放的

### Actual behavior

实际下载的时候每次报"Sign in to confirm that you're not a bot"

### Logs

严重: getOriginStreamByWebUrl:https://www.youtube.com/watch?v=q6Ni0_gBdOk failed,please check the web url is correct!
org.schabi.newpipe.extractor.exceptions.ContentNotAvailableException: Got error: "Sign in to confirm that you're not a bot"
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.checkPlayabilityStatus(YoutubeStreamExtractor.java:899)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:785)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:60)

**Comment by evenly99** [comment]
It has always been possible to download youtube videos using NewPipeExtractor. Got error: "Sign in to confirm that you're not a bot" has been reported recently.
I have updated NewPipeExtractor to the latest version

**Comment by evenly99** [comment]
I hope I can download a youtube video like https://www.youtube.com/watch?v=q6Ni0_gBdOk. This video can be played normally when opened on the web. When actually downloading, it will say "Sign in to confirm that you're not a bot"
