### ISSUE TITLE
SoundCloudService D6.d: Could not get client id

### ISSUE THREAD

**Issue by uzu09811** [TeamNewPipe/NewPipeExtractor#1232]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipeExtractor/releases/latest).
- [X] I am aware that this issue is being opened for the NewPipe Extractor, NOT the [app](https://github.com/TeamNewPipe/NewPipe), and my bug report will be dismissed otherwise.
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipeExtractor/issues) or [closed](https://github.com/TeamNewPipe/NewPipeExtractor/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.2

### Steps to reproduce the bug

My codes is

```class SoundCloudService {
    private val soundCloudSearcher = SoundCloudSearcher()
    private val streamExtractorHelper = StreamExtractorHelper()

    suspend fun searchAndFetchAudioStream(query: String): String? {
        return withContext(Dispatchers.IO) {
            // Search for the song using the SoundCloudSearcher
            val searchResults = soundCloudSearcher.searchSong(query)

            // Get the first item's URL (if it exists) and extract the streaming URL
            val firstItem = searchResults?.firstOrNull()
            firstItem?.url?.let { songUrl ->
                // Use the StreamExtractorHelper to extract the direct streaming URL
                streamExtractorHelper.getStreamingUrl(songUrl)
            }
        }
    }
}```

```class SoundCloudSearcher {

    init {
        // Initialize NewPipe with your custom downloader
        NewPipe.init(CustomDownloader)
    }

    fun searchSong(query: String): List<InfoItem>? {
        val soundCloudService = NewPipe.getService(1) as SoundcloudService

        // Create a SearchQueryHandler from the query
        val searchQueryHandler = soundCloudService.getSearchQHFactory().fromQuery(query)

        // Get the SearchExtractor from the SearchQueryHandler
        val searchExtractor = soundCloudService.getSearchExtractor(searchQueryHandler)

        return try {
            // Fetch the initial page to get items
            val initialPage = searchExtractor.getInitialPage()
            Log.w("SoundCloudSearcher", "Found ${initialPage.items.size} items")
            initialPage.items // Return the items from the initial page
        } catch (e: Exception) {
            // Handle exceptions (e.g., ExtractionException, IOException)
            Log.e("SoundCloudSearcher", "Error while searching for song: ${e.message}", e)
            null
        }
    }
}```

```class StreamExtractorHelper {

    init {
        // Initialize NewPipe (required for extraction)
        NewPipe.init(CustomDownloader)
    }

    suspend fun getStreamingUrl(songUrl: String): String? {
        val soundCloudService = SoundcloudService(0)
        val linkHandler = soundCloudService.getStreamLHFactory().fromUrl(songUrl)

        // Get Stream Extractor for the SoundCloud track
        val streamExtractor = soundCloudService.getStreamExtractor(linkHandler) as SoundcloudStreamExtractor

        // Fetch the page to extract necessary data
        streamExtractor.onFetchPage(CustomDownloader)

        // Extract the audio streams and return the first available URL
        val audioStreams = streamExtractor.audioStreams
        return audioStreams.firstOrNull()?.url // Return the first audio stream URL
    }
}```

### Expected behavior

Crashes due to null pointer exception and then showing D6.d: Could not get client id

### Actual behavior

As said in Expected behavior

### Screenshots/Screen recordings

Null

### Logs

2024-10-04 14:38:16.804 29198 6668 io.github.notify E fetchStreamingUrl : Error while fetching streaming URL
D6.d: Could not get client id
	at L6.a.J(Unknown Source:132)
	at io.github.notify.network.SoundCloudSearcher.searchSong(Unknown Source:48)
	at io.github.notify.network.SoundCloudService$searchAndFetchAudioStream$2.invokeSuspend(Unknown Source:34)
	at io.github.notify.network.SoundCloudService$searchAndFetchAudioStream$2.invoke(SourceFile:1)
	at io.github.notify.network.SoundCloudService$searchAndFetchAudioStream$2.invoke(SourceFile:2)
	at H1.a.H(Unknown Source:4)
	at O5.H.D(Unknown Source:73)
	at io.github.notify.network.SoundCloudService.searchAndFetchAudioStream(Unknown Source:8)
	at io.github.notify.fragments.MediaPlayerFragment$fetchStreamingUrl$2.invokeSuspend(Unknown Source:265)
	at x5.a.resumeWith(Unknown Source:7)
	at O5.O.run(Unknown Source:112)
	at B3.r.run(Unknown Source:113)
	at V5.k.run(Unknown Source:2)
	at V5.a.run(Unknown Source:95)
Caused by: D6.b: Couldn't extract client id
	at J6.a.a(Unknown Source:130)
	at L6.a.J(Unknown Source:90)
	... 13 more

### Additional information

Null

**Comment by uzu09811** [comment]
Actually I forgot to do fetch before accessing the data so that's my fault, sorry 😐
