### ISSUE TITLE
Unable to play get youtube url Null pointer

### ISSUE THREAD

**Issue by sanjeev00** [TeamNewPipe/NewPipeExtractor#224]
I am unable to get youtube url I am getting Nullpointer exception in Newpipe.getDownloader()
Can Someone give me the exact code to get youtube mp4 url.
This is urgent

**Comment by Stypox** [comment]
You have to manually provide a user-implemented downloader. See the downloader class in the extraxtor tests for more information

**Comment by Stypox** [comment]
Here is the DownloaderTestImpl class, that inherits Downloader: https://github.com/TeamNewPipe/NewPipeExtractor/blob/dev/extractor/src/test/java/org/schabi/newpipe/DownloaderTestImpl.java

**Comment by sanjeev00** [comment]
I am beginner and It would really helpful if I can get Sample code.I tried to Understand the documentation but I couldn't. Sorry

**Comment by sanjeev00** [comment]
I tried to implement using the link you provided 







        NewPipe.init(DownloaderTestImpl.getInstance());`
        String url = "https://www.youtube.com/watch?v=ZSZwDARaQYI";

        try {


            YoutubeStreamExtractor extractor = (YoutubeStreamExtractor) YouTube.getStreamExtractor(url);
            extractor.fetchPage();
        }
        catch (ExtractionException e)
        {

        }
        catch (IOException e){

        }
But I ended up with NullpointerException
`Process: org.nesoacademy, PID: 5599
    java.lang.NullPointerException: Attempt to invoke interface method 'void com.android.okhttp.internal.http.HttpStream.writeRequestHeaders(com.android.okhttp.Request)' on a null object reference
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:593)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:471)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(Unknown Source:0)
        at org.nesoacademy.DownloaderTestImpl.execute(DownloaderTestImpl.java:115)
        at org.schabi.newpipe.extractor.downloader.Downloader.get(Downloader.java:70)
        at org.schabi.newpipe.extractor.downloader.Downloader.get(Downloader.java:42)
        at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:694)
        at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:54)
        at org.nesoacademy.ui.home.Lecture.extract(Lecture.java:625)
        at org.nesoacademy.video_item_adaptor.swapVideo(video_item_adaptor.java:98)
        at org.nesoacademy.video_item_adaptor$2$1.onDataChange(video_item_adaptor.java:213)
        at com.google.firebase.database.Query$1.onDataChange(com.google.firebase:firebase-database@@17.0.0:184)
        at com.google.firebase.database.core.ValueEventRegistration.fireEvent(com.google.firebase:firebase-database@@17.0.0:75)
        at com.google.firebase.database.core.view.DataEvent.fire(com.google.firebase:firebase-database@@17.0.0:63)
        at com.google.firebase.database.core.view.EventRaiser$1.run(com.google.firebase:firebase-database@@17.0.0:55)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:171)
        at android.app.ActivityThread.main(ActivityThread.java:6651)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
2019`

**Comment by sanjeev00** [comment]
> Here is the DownloaderTestImpl class, that extends Downloader: https://github.com/TeamNewPipe/NewPipeExtractor/blob/dev/extractor/src/test/java/org/schabi/newpipe/DownloaderTestImpl.java
I Figured it out. It now works.Thanks a lot You saved my life

**Comment by Stypox** [comment]
You are welcome 😃

**Comment by arunmandal53** [comment]
@sanjeev00 please mention what you solved this.

**Comment by arunmandal53** [comment]
for those having still null use new Thread instead of main thread.

**Comment by manojkumarpaladugu** [comment]
> > Here is the DownloaderTestImpl class, that extends Downloader: https://github.com/TeamNewPipe/NewPipeExtractor/blob/dev/extractor/src/test/java/org/schabi/newpipe/DownloaderTestImpl.java
> 
> I Figured it out. It now works.Thanks a lot You saved my life

Sanjeev, i am also facing same issue, can you please describe how to fix it?
