### ISSUE TITLE
ParsingException is thrown on deleted or non-existant channels

### ISSUE THREAD

**Issue by Stypox** [TeamNewPipe/NewPipeExtractor#228]
Try to open [this deleted channel](https://www.youtube.com/channel/UChlFShtShMTo9PUHRkasR6A) in NewPipe: instead of getting a message explaining that the channel was deleted, the app crashes. We should add a method that checks whether the channel exists and is valid or not.

## Exception
* __User Action:__ requested channel
* __Request:__ https://www.youtube.com/channel/UChlFShtShMTo9PUHRkasR6A
* __Content Language:__ GB
* __Service:__ YouTube
* __Version:__ 0.17.4
* __OS:__ Linux Android 7.0 - 24

<details><summary><b>Crash log</b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get channel name
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor.getName(YoutubeChannelExtractor.java:106)
	at org.schabi.newpipe.extractor.channel.ChannelInfo.getInfo(ChannelInfo.java:62)
	at org.schabi.newpipe.extractor.channel.ChannelInfo.getInfo(ChannelInfo.java:49)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getChannelInfo$4(ExtractorHelper.java:123)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$u5W7VszTe8AoEexIsFM9huQfbkM.call(lambda)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14479)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:776)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jsoup.nodes.Node.attr(java.lang.String)' on a null object reference
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor.getName(YoutubeChannelExtractor.java:104)
	... 28 more

```
</p></details>
<hr>

**Comment by Redirion** [comment]
`    public String getYoutubeError() throws ParsingException {
        try {
            return doc.select("div.yt-alert-message").first().text();
        } catch (Exception e) {
            throw new ParsingException("Could not get youtube error", e);
        }
    }`

with this method the error message of youtube can be obtained. "This account has been terminated due to multiple or severe violations of YouTube's policy prohibiting hate speech." This message is localized and would be perfet to be displayed to the user instead of the crash.

I have tested it by adding it to the YoutubeChannelExtractor and running it with an adjusted YoutubeChannelExtractorTest., but I don*t yet know how to integrate it seamlessly.

**Comment by B0pol** [comment]
[I think it's fixed now](https://github.com/TeamNewPipe/NewPipeExtractor/blob/1b522304c12f966b8adde5664bfb14a6e27545be/extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeChannelExtractor.java#L109). It throws ContentNotAvailableException and gather error message via [YoutubeParsingHelper.defaultAlertChecks()](https://github.com/TeamNewPipe/NewPipeExtractor/blob/1b522304c12f966b8adde5664bfb14a6e27545be/extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/linkHandler/YoutubeParsingHelper.java#L487).
