### ISSUE TITLE
Can't load comments from an invidious link (TeamNewPipe/NewPipe#2817)

### ISSUE THREAD

**Issue by B0pol** [TeamNewPipe/NewPipeExtractor#235]
See TeamNewPipe/NewPipe#2817
If you open any invidious link, it won't load comments and will produce and error log

Here is the error log
## Exception
* __User Action:__ requested comments
* __Request:__ https://invidio.us/watch?v=ia1iuXbEaYQ
* __Content Language:__ FR
* __Service:__ YouTube
* __Version:__ 0.18.0
* __OS:__ Linux Android 8.1.0 - 27

<details><summary><b>Crash log</b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Malformed unacceptable url: https://invidio.us/watch?v=ia1iuXbEaYQ
	at org.schabi.newpipe.extractor.linkhandler.LinkHandlerFactory.fromUrl(LinkHandlerFactory.java:53)
	at org.schabi.newpipe.extractor.linkhandler.ListLinkHandlerFactory.fromUrl(ListLinkHandlerFactory.java:37)
	at org.schabi.newpipe.extractor.linkhandler.ListLinkHandlerFactory.fromUrl(ListLinkHandlerFactory.java:30)
	at org.schabi.newpipe.extractor.StreamingService.getCommentsExtractor(StreamingService.java:259)
	at org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:25)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getCommentsInfo$6(ExtractorHelper.java:139)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$4SXML3L5j2DhMfS2ZK06RZb2iyE.call(Unknown Source:4)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14479)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

```
</p></details>
<hr>
How to reproduce:
pick any invidious link and open it with newpipe (either you pick an invidious link, or you pick a youtube link and make it invidious link by changing youtube.com by invidio.us)

**Comment by B0pol** [comment]
I guess I found why:
[In YouTubeStreamLinkHandlerFactory](https://github.com/TeamNewPipe/NewPipeExtractor/blob/dev/extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/linkHandler/YoutubeStreamLinkHandlerFactory.java), Invidious is supported, but
[in YoutubeCommentsLinkHandlerFactory](https://github.com/TeamNewPipe/NewPipeExtractor/blob/dev/extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/linkHandler/YoutubeCommentsLinkHandlerFactory.java), there is nothing about Invidous.
Especially in getID() method

I'm new to the extractor ~~even newpipe in fact~~, how can I test changes (before testing in the app)? If I change the youtube url in [YoutubeCommentsExtractorTest](https://github.com/TeamNewPipe/NewPipeExtractor/blob/dev/extractor/src/test/java/org/schabi/newpipe/extractor/services/youtube/YoutubeCommentsExtractorTest.java) with an invidious url, the tests should be ok?
and when it's ok with this, I now test in the app like said [in the doc](https://teamnewpipe.github.io/documentation/04_Run_changes_in_App/) and I make a PR?

**Comment by Stypox** [comment]
Sometimes the implementation URL provided by JitPack does not work, in that case try `implementation 'com.github.YourUsername:YourRepoName:FullCommitHash'`

**Comment by Stypox** [comment]
@B0pol Forgot to say that by proceeding as you explained you should be good to go. Thanks!
