### ISSUE TITLE
[Soundcloud] Could not get any stream error on some tracks

### ISSUE THREAD

**Issue by B0pol** [TeamNewPipe/NewPipeExtractor#250]
Hi
Steps to reproduce:
Go in Soundcloud in NewPipe.
Search for « Dua Lipa »
Go on her channel page
Try to open « Future Nostalgia », or « Don't start now (Kungs Remix) », or « Don't Start Now », or a lot of other video on this page

## Exception
* __User Action:__ requested stream
* __Request:__ https://soundcloud.com/dualipa/future-nostalgia
* __Content Language:__ FR
* __Service:__ SoundCloud
* __Version:__ 0.18.2
* __OS:__ Linux Android 8.1.0 - 27

<details><summary><b>Crash log</b></summary><p>

```
org.schabi.newpipe.extractor.stream.StreamInfo$StreamExtractException: Could not get any stream. See error variable to get further details.
	at org.schabi.newpipe.extractor.stream.StreamInfo.extractStreams(StreamInfo.java:188)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:68)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:60)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:115)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(Unknown Source:4)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14479)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

```
</p></details>
<hr>

Might be related issue:
It shows content not available, even though if it's available on SoundCloud website.
Steps to reproduce:
Same as above, except you have to open « Don't start Now (Pink Panda Remix) »
or
any music on selena gomez channel

**Comment by TobiGr** [comment]
We only list the mp3 streams, but there are also opus streams. When there are no mp3 streams, this error might occur. I noticed this while fixing the stream access recently, but did not have time to dive deeper into it. 

The last catch part is the interesting one.
https://github.com/TeamNewPipe/NewPipeExtractor/blob/f8d117f6cdf6325240e4856ba84c86ce4485ca02/extractor/src/main/java/org/schabi/newpipe/extractor/services/soundcloud/SoundcloudStreamExtractor.java#L174-L190

**Comment by wb9688** [comment]
I found out adding SoundCloud's Opus stuff is harder than I thought, as SoundCloud only provides them (and MP3 as well) as HLS in that case, which NewPipe only supports for live streams. See #273

**Comment by B0pol** [comment]
Shouldn't we display "Content not available" instead of just a crash?

**Comment by opusforlife2** [comment]
For URL types that are _known_ to be bad, how about a generic error message? Something like:

"Newpipe can't open this yet. It will come in a future release."

This string could then be used wherever appropriate.

**Comment by B0pol** [comment]
> For URL types that are _known_ to be bad, how about a generic error message? Something like:
> 
> "Newpipe can't open this yet. It will come in a future release."
> 
> This string could then be used wherever appropriate.

It's done. See https://github.com/TeamNewPipe/NewPipe/pull/3300.

I'm closing this issue as https://github.com/TeamNewPipe/NewPipe/pull/3300 and #300 partially fixed it. For the real fix with support, there is already a ticket for it: #273.
