### ISSUE TITLE
NPEs in 0.18.6

### ISSUE THREAD

**Issue by artsemionov** [TeamNewPipe/NewPipeExtractor#278]
Pretty rare, but still happens:
at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor.getPage (YoutubeChannelExtractor.java:200)
at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.getPage (YoutubeSearchExtractor.java:110)

**Comment by wb9688** [comment]
That only happens after scrolling, right? Could you link a channel or search query where I could eaily reproduce that?

**Comment by artsemionov** [comment]
Yes.
Try this channel: https://www.youtube.com/channel/UCAUprtSLJt6YEtBjiZRAHIg
It happened for me after load + 3 page scrolls.

For search: "en qué país está desarrollando la vacuna para el coronavirus" on the second page.

**Comment by wb9688** [comment]
@artsemionov: Thanks! I could reproduce that and I'll look into it tomorrow.

**Comment by wb9688** [comment]
@artsemionov: It should be fixed in ecc6ba592eab64ab5910f87ab05435f807cf6237.

**Comment by artsemionov** [comment]
Thanks! Will try this in 0.18.7

**Comment by artsemionov** [comment]
Here is one more, extremelly rare:
java.lang.NullPointerException
at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor.collectStreamsFrom (YoutubeChannelExtractor.java:225)
at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor.getPage (YoutubeChannelExtractor.java:202)

https://www.youtube.com/channel/UCXXBi6rvC-u8VDZRD23F7tw

**Comment by wb9688** [comment]
@artsemionov: Fixed in my tabs PR now.

**Comment by artsemionov** [comment]
I use https://github.com/yausername/NewPipeREST with 0.18.6 and your fixes applied i.e         ```
if (ajaxJson.getObject(1).getObject("response").getObject("continuationContents") == null)
            return null;
```

Stack trace:
```
java.lang.NullPointerException
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.getPage(YoutubeSearchExtractor.java:115)
	at org.schabi.newpipe.extractor.search.SearchInfo.getMoreItems(SearchInfo.java:62)
```

I have `collectStreamsFrom(collector, itemSectionRenderer.getArray("contents"));` at 115, so itemSectionRenderer is null.

Sample queries:
uganda comedy
el barrio
musica cristiana
canciones de animatronicos

**Comment by artsemionov** [comment]
Here is json: https://pastebin.com/giwC5Qp2
Seems itemSectionContinuation is renamed to sectionListContinuation in some situations.

**Comment by wb9688** [comment]
@artsemionov: Could you try #317?

**Comment by artsemionov** [comment]
@wb9688 You want me to just test this PR? Or will it help with above exception?
