### ISSUE TITLE
Search Exception

### ISSUE THREAD

**Issue by MehmetSait** [TeamNewPipe/NewPipeExtractor#446]
when search videos always get below exception

org.schabi.newpipe.extractor.exceptions.ParsingException: Got HTML document, expected JSON response (latest url was: "https://www.youtube.com/supported_browsers?next_url=https://www.youtube.com/results?search_query%3Dcartoni+italiani+2019&gl=TR&pbj=1")
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getValidJsonResponseBody(YoutubeParsingHelper.java:513)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getJsonResponse(YoutubeParsingHelper.java:526)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.onFetchPage(YoutubeSearchExtractor.java:67)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:56)
	at org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:29)

**Comment by Stypox** [comment]
Fill in the template

**Comment by opusforlife2** [comment]
It's here: https://github.com/TeamNewPipe/NewPipeExtractor/issues/new/choose

**Comment by opusforlife2** [comment]
@Stypox This is the Extractor repo. There is no template.

@TobiGr We should have templates for this repo too, no?
