### ISSUE TITLE
TimeAgoParser getting NoClassDefFoundError

### ISSUE THREAD

**Issue by fabiano-araujo** [TeamNewPipe/NewPipeExtractor#464]
```
CustomActivityOnCrash: App has crashed, executing CustomActivityOnCrash's UncaughtExceptionHandler
    java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/ZoneOffset;
        at org.schabi.newpipe.extractor.localization.TimeAgoParser.<init>(TimeAgoParser.java:32)
        at org.schabi.newpipe.extractor.localization.TimeAgoPatternsManager.getTimeAgoParserFor(TimeAgoPatternsManager.java:23)
        at org.schabi.newpipe.extractor.StreamingService.getTimeAgoParser(StreamingService.java:372)
        at org.schabi.newpipe.extractor.Extractor.getTimeAgoParser(Extractor.java:143)
        at br.com.fabiano.developer.playyourmusic.utils.extractor.YoutubeStreamExtractor.getNextStream(YoutubeStreamExtractor.java:632)
        at br.com.fabiano.developer.playyourmusic.utils.extractor.YoutubeStreamExtractor.getRelatedStreams(YoutubeStreamExtractor.java:650)
```
the error in this line `now = OffsetDateTime.now(ZoneOffset.UTC);` and only occurs on older devices.

**Comment by Stypox** [comment]
You have to enable library desugaring, since NewPipeExtractor uses Java 8, which is not available on older devices. See NewPipe's app/build.gradle for more details
