### ISSUE TITLE
PlaylistExtractor crashes on lower Android versions with v0.20.4

### ISSUE THREAD

**Issue by Amidos** [TeamNewPipe/NewPipeExtractor#470]
PlaylistExtractor started crashing for me on Android 4.* and Android 6.* devices. Test on Android 9+ is successful.

My code:
`PlaylistExtractor searchExtractor =  youtube.getPlaylistExtractor(url);
  searchExtractor.fetchPage();
  ListExtractor.InfoItemsPage<StreamInfoItem> page = searchExtractor.getInitialPage();`

Android 4.* exception:
` Caused by: java.lang.VerifyError: org/schabi/newpipe/extractor/services/youtube/YoutubeParsingHelper
        at org.schabi.newpipe.extractor.services.youtube.linkHandler.YoutubePlaylistLinkHandlerFactory.getId(YoutubePlaylistLinkHandlerFactory.java:30)
        at org.schabi.newpipe.extractor.services.youtube.linkHandler.YoutubePlaylistLinkHandlerFactory.onAcceptUrl(YoutubePlaylistLinkHandlerFactory.java:64)
        at org.schabi.newpipe.extractor.linkhandler.LinkHandlerFactory.acceptUrl(LinkHandlerFactory.java:97)
        at org.schabi.newpipe.extractor.linkhandler.LinkHandlerFactory.fromUrl(LinkHandlerFactory.java:70)
        at org.schabi.newpipe.extractor.linkhandler.ListLinkHandlerFactory.fromUrl(ListLinkHandlerFactory.java:44)
        at org.schabi.newpipe.extractor.linkhandler.ListLinkHandlerFactory.fromUrl(ListLinkHandlerFactory.java:37)
        at org.schabi.newpipe.extractor.StreamingService.getPlaylistExtractor(StreamingService.java:258)`

Android 6.* exception:
`       Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/ZoneOffset;
        at org.schabi.newpipe.extractor.localization.TimeAgoParser.<init>(TimeAgoParser.java:32)
        at org.schabi.newpipe.extractor.localization.TimeAgoPatternsManager.getTimeAgoParserFor(TimeAgoPatternsManager.java:23)
        at org.schabi.newpipe.extractor.StreamingService.getTimeAgoParser(StreamingService.java:372)
        at org.schabi.newpipe.extractor.Extractor.getTimeAgoParser(Extractor.java:143)
        at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubePlaylistExtractor.collectStreamsFrom(YoutubePlaylistExtractor.java:242)
        at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubePlaylistExtractor.getInitialPage(YoutubePlaylistExtractor.java:194)`

**Comment by Stypox** [comment]
You need to use library desugaring, since the extractor now requires Java 8 which is not available on old Android versions

**Comment by Amidos** [comment]
Just realized it by looking at NewPipe gradle file. Thanks for your answer!
