### ISSUE TITLE
Failed resolution of: Ljava/time/OffsetDateTime

### ISSUE THREAD

**Issue by tianxuefeng** [TeamNewPipe/NewPipeExtractor#478]
Crash in some devices, e,g HuaWei P9 Pro...

V0.20.6    

 Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/OffsetDateTime;
        at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.parseDateFrom(YoutubeParsingHelper.java:185)
        at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getUploadDate(YoutubeStreamExtractor.java:200)
        at org.schabi.newpipe.extractor.stream.StreamInfo.extractOptionalData(StreamInfo.java:266)
        at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:73)
        at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)

**Comment by tianxuefeng** [comment]
desugar_jdk_libs is needed!
