### ISSUE TITLE
Trending Page broken - Could not get Trending name

### ISSUE THREAD

**Issue by FireMasterK** [TeamNewPipe/NewPipeExtractor#581]
```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get Trending name
        at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeTrendingExtractor.getName(YoutubeTrendingExtractor.java:84)
        at org.schabi.newpipe.extractor.kiosk.KioskInfo.getInfo(KioskInfo.java:70)
        at org.schabi.newpipe.extractor.kiosk.KioskInfo.getInfo(KioskInfo.java:58)
        at me.kavin.piped.utils.ResponseHelper.trendingResponse(ResponseHelper.java:212)
        at me.kavin.piped.Main.lambda$main$13(Main.java:220)
        at me.kavin.piped.Main$$Lambda$116/0x00000000605118b0.apply(Unknown Source)
```

This can now be replicated all the time now, previously was one in x random requests.

**Comment by FireMasterK** [comment]
Related: https://github.com/TeamNewPipe/NewPipe/issues/5893, https://github.com/TeamNewPipe/NewPipe/issues/5895, https://github.com/TeamNewPipe/NewPipe/issues/5872#issuecomment-805357876
