### ISSUE TITLE
SoundcloudParsingHelperTest > assertThatHardcodedClientIdIsValid FAILED

### ISSUE THREAD

**Issue by litetex** [TeamNewPipe/NewPipeExtractor#744]
This test currently fails on all CI builds, e.g. https://github.com/TeamNewPipe/NewPipeExtractor/runs/4093194284?check_suite_focus=true

```
 org.schabi.newpipe.extractor.services.soundcloud.SoundcloudParsingHelperTest > assertThatHardcodedClientIdIsValid FAILED
    java.lang.AssertionError: Hardcoded client id is not valid anymore
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.assertTrue(Assert.java:42)
        at org.schabi.newpipe.extractor.services.soundcloud.SoundcloudParsingHelperTest.assertThatHardcodedClientIdIsValid(SoundcloudParsingHelperTest.java:19)

...

1635 tests completed, 1 failed, 122 skipped
```

**Comment by TiA4f8R** [comment]
Fixed with #745.
