### ISSUE TITLE
[media.ccc.de] No streams for live streams

### ISSUE THREAD

**Issue by TobiGr** [TeamNewPipe/NewPipeExtractor#766]
## Exception
* __User Action:__ requested stream
* __Request:__ https://streaming.media.ccc.de/rc3/cbase
* __Content Country:__ DE
* __Content Language:__ de
* __App Language:__ en
* __Service:__ media.ccc.de
* __Version:__ 0.21.15
* __OS:__ Linux Android 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.stream.StreamInfo$StreamExtractException: Could not get any stream. See error variable to get further details.
	at org.schabi.newpipe.extractor.stream.StreamInfo.extractStreams(StreamInfo.java:194)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:72)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:116)
	at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$YTHJjScxCJNO1LTCqs3IKy35iyY(Unknown Source:0)
	at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda6.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15753)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

```
</details>
<hr>

**Comment by TiA4f8R** [comment]
The following JSON is returned for this stream, if it helps for debugging:

```json
{
    "slug": "cbase",
    "schedulename": "c-base",
    "thumb": "https://cdn.c3voc.de/thumbnail/cbase/thumb.jpeg",
    "poster": "https://cdn.c3voc.de/thumbnail/cbase/poster.jpeg",
    "link": "https://streaming.media.ccc.de/rc3/cbase",
    "display": "c-base",
    "stream": "cbase",
    "talks": {
        "current": {
            "fstart": "2021-12-27T13:30:00+01:00",
            "fend": "2021-12-27T14:15:00+01:00",
            "tstart": "13:30",
            "tend": "14:15",
            "start": 1640608200,
            "end": 1640610900,
            "offset": 3600,
            "duration": 2700,
            "title": "StVO hacken - Verkehrswende selbermachen",
            "speaker": "Laura Fritsche",
            "room_known": true,
            "optout": false
        },
        "next": {
            "fstart": "2021-12-27T16:00:00+01:00",
            "fend": "2021-12-27T16:30:00+01:00",
            "tstart": "16:00",
            "tend": "16:30",
            "start": 1640617200,
            "end": 1640619000,
            "offset": 3600,
            "duration": 1800,
            "title": "Facebook Files Explained",
            "speaker": "Svea",
            "room_known": true,
            "optout": false
        }
    },
    "streams": [
        {
            "slug": "hls-native",
            "display": "c-base ",
            "type": "hls",
            "isTranslated": false,
            "videoSize": null,
            "urls": {}
        },
        {
            "slug": "audio-native",
            "display": "c-base Audio",
            "type": "audio",
            "isTranslated": false,
            "videoSize": null,
            "urls": {
                "hls": {
                    "display": "HLS",
                    "tech": "AAC, VBR",
                    "url": "https://cdn.c3voc.de/hls/cbase/segment_Native.m3u8"
                }
            }
        },
        {
            "slug": "hd-native",
            "display": "c-base FullHD Video",
            "type": "video",
            "isTranslated": false,
            "videoSize": [
                1920,
                1080
            ],
            "urls": {
                "hls": {
                    "display": "HLS",
                    "tech": "1920x1080, h264+AAC im MPEG-TS-Container via HTTP, 3 MBit/s",
                    "url": "https://cdn.c3voc.de/hls/cbase/native_hd.m3u8"
                }
            }
        }
    ]
}
```

Full JSON for reference: [mediaccc_livestreams.json.txt](https://github.com/TeamNewPipe/NewPipeExtractor/files/7780362/mediaccc_livestreams.json.txt)

The issue is probably in `getAudioStreams` or `getVideoStreams` method of `MediaCCCLiveStreamExtractor`.

**Comment by TobiGr** [comment]
I am currently on it

**Comment by yoshimo** [comment]
> I am currently on it

Would be nice to resolve this with events coming up, especially the annual big event.
