### ISSUE TITLE
Youtube parse error

### ISSUE THREAD

**Issue by viyarda** [TeamNewPipe/NewPipeExtractor#784]
org.schabi.newpipe.extractor.utils.Parser$RegexException: failed to find pattern "b=a\.get\("n"\)\)&&\(b=(\w+)\(b\),a\.set\("n",b\)"

**Comment by viyarda** [comment]
at org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:74)
at org.schabi.newpipe.extractor.utils.Parser.matchGroup1(Parser.java:58)
at org.schabi.newpipe.extractor.services.youtube.YoutubeThrottlingDecrypter.parseDecodeFunctionName(YoutubeThrottlingDecrypter.java:69)
at org.schabi.newpipe.extractor.services.youtube.YoutubeThrottlingDecrypter.<init>(YoutubeThrottlingDecrypter.java:56)
at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getVideoStreams(YoutubeStreamExtractor.java:532)

**Comment by sultanahamer** [comment]
Same exception for me as well on 0.21.12 and on 0.21.11

**Comment by opusforlife2** [comment]
@viyarda Since Youtube breaking is such a major issue, it's usually reported and pinned in the Newpipe repo. That's been done now. Thanks for reporting, though, and for pointing out the specific error.
