### ISSUE TITLE
Failing to parse youtube url: https://www.youtube.com/watch?v=AbCWHZljhkM

### ISSUE THREAD

**Issue by sultanahamer** [TeamNewPipe/NewPipeExtractor#834]
This is happening on **0.21.14**

**Here is the stacktrace**:
```
org.schabi.newpipe.extractor.utils.Parser$RegexException: failed to find pattern "var $x=\[(.+?)\];"
        at org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:74) ~[extractor-v0.21.14.jar:na]
        at org.schabi.newpipe.extractor.utils.Parser.matchGroup1(Parser.java:58) ~[extractor-v0.21.14.jar:na]
        at org.schabi.newpipe.extractor.services.youtube.YoutubeThrottlingDecrypter.parseDecodeFunctionName(YoutubeThrottlingDecrypter.java:79) ~[extractor-v0.21.14.jar:na]
        at org.schabi.newpipe.extractor.services.youtube.YoutubeThrottlingDecrypter.<init>(YoutubeThrottlingDecrypter.java:56) ~[extractor-v0.21.14.jar:na]
        at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getVideoStreams(YoutubeStreamExtractor.java:497) ~[extractor-v0.21.14.jar:na]
```

**Comment by Aurangzeb365** [comment]
org.schabi.newpipe.extractor.playlist.PlaylistInfoItem cannot be cast to org.schabi.newpipe.extractor.stream.StreamInfoItem
This is also happening on 0.21.14

**Comment by sseodate** [comment]
Yes since yesterday. Extractor not work anymore

**Comment by xibr** [comment]
use this
```
com.github.TeamNewPipe.NewPipeExtractor:NewPipeExtractor:b77c72fb88
```

**Comment by sseodate** [comment]
Please release the version update Tobi.

**Comment by TiA4f8R** [comment]
Version 0.22.0 has been released. Use this extraction version to solve the issue.
