### ISSUE TITLE
Parse youtube error, Could not get audio streams

### ISSUE THREAD

**Issue by viyarda** [TeamNewPipe/NewPipeExtractor#895]
Could not get audio streams
     Caused by: org.mozilla.javascript.EvaluatorException: unterminated string literal (Yka#18)
        at org.mozilla.javascript.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:79)
        at org.mozilla.javascript.DefaultErrorReporter.error(DefaultErrorReporter.java:66)
        at org.mozilla.javascript.Parser.addError(Parser.java:257)
        at org.mozilla.javascript.Parser.addError(Parser.java:228)
        at org.mozilla.javascript.Parser.addError(Parser.java:223)
        at org.mozilla.javascript.TokenStream.getToken(TokenStream.java:942)
        at org.mozilla.javascript.Parser.peekToken(Parser.java:404)
        at org.mozilla.javascript.Parser.arrayLiteral(Parser.java:3191)
        at org.mozilla.javascript.Parser.primaryExpr(Parser.java:3045)
        at org.mozilla.javascript.Parser.memberExpr(Parser.java:2671)
        at org.mozilla.javascript.Parser.unaryExpr(Parser.java:2574)
        at org.mozilla.javascript.Parser.expExpr(Parser.java:2494)
        at org.mozilla.javascript.Parser.mulExpr(Parser.java:2477)
        at org.mozilla.javascript.Parser.addExpr(Parser.java:2463)
        at org.mozilla.javascript.Parser.shiftExpr(Parser.java:2446)
        at org.mozilla.javascript.Parser.relExpr(Parser.java:2424)
        at org.mozilla.javascript.Parser.eqExpr(Parser.java:2400)
        at org.mozilla.javascript.Parser.bitAndExpr(Parser.java:2391)
        at org.mozilla.javascript.Parser.bitXorExpr(Parser.java:2382)
        at org.mozilla.javascript.Parser.bitOrExpr(Parser.java:2373)
        at org.mozilla.javascript.Parser.andExpr(Parser.java:2364)
        at org.mozilla.javascript.Parser.orExpr(Parser.java:2355)
        at org.mozilla.javascript.Parser.condExpr(Parser.java:2322)
        at org.mozilla.javascript.Parser.assignExpr(Parser.java:2280)
        at org.mozilla.javascript.Parser.variables(Parser.java:2128)
        at org.mozilla.javascript.Parser.statementHelper(Parser.java:1197)
        at org.mozilla.javascript.Parser.statement(Parser.java:1104)
        at org.mozilla.javascript.Parser.parseFunctionBody(Parser.java:736)
        at org.mozilla.javascript.Parser.function(Parser.java:911)
        at org.mozilla.javascript.Parser.function(Parser.java:845)
        at org.mozilla.javascript.Parser.primaryExpr(Parser.java:3041)
        at org.mozilla.javascript.Parser.memberExpr(Parser.java:2671)
        at org.mozilla.javascript.Parser.unaryExpr(Parser.java:2574)
        at org.mozilla.javascript.Parser.expExpr(Parser.java:2494)
        at org.mozilla.javascript.Parser.mulExpr(Parser.java:2477)
        at org.mozilla.javascript.Parser.addExpr(Parser.java:2463)
        at org.mozilla.javascript.Parser.shiftExpr(Parser.java:2446)
        at org.mozilla.javascript.Parser.relExpr(Parser.java:2424)
        at org.mozilla.javascript.Parser.eqExpr(Parser.java:2400)
        at org.mozilla.javascript.Parser.bitAndExpr(Parser.java:2391)
        at org.mozilla.javascript.Parser.bitXorExpr(Parser.java:2382)
        at org.mozilla.javascript.Parser.bitOrExpr(Parser.java:2373)
        at org.mozilla.javascript.Parser.andExpr(Parser.java:2364)
        at org.mozilla.javascript.Parser.orExpr(Parser.java:2355)
2022-08-15 08:36:27.247 14403-26151/com.musixmusicx D/YTBExtractorManager:     at org.mozilla.javascript.Parser.condExpr(Parser.java:2322)
        at org.mozilla.javascript.Parser.assignExpr(Parser.java:2280)
        at org.mozilla.javascript.Parser.assignExpr(Parser.java:2303)
        at org.mozilla.javascript.Parser.expr(Parser.java:2263)
        at org.mozilla.javascript.Parser.nameOrLabel(Parser.java:2021)
        at org.mozilla.javascript.Parser.statementHelper(Parser.java:1240)
        at org.mozilla.javascript.Parser.statement(Parser.java:1104)
        at org.mozilla.javascript.Parser.parse(Parser.java:632)
        at org.mozilla.javascript.Parser.parse(Parser.java:562)
        at org.mozilla.javascript.Context.parse(Context.java:2470)
        at org.mozilla.javascript.Context.compileImpl(Context.java:2401)
        at org.mozilla.javascript.Context.compileString(Context.java:1369)
        at org.mozilla.javascript.Context.compileString(Context.java:1357)
        at org.mozilla.javascript.Context.evaluateString(Context.java:1135)
        at org.schabi.newpipe.extractor.utils.JavaScript.run(JavaScript.java:20)
        at org.schabi.newpipe.extractor.services.youtube.YoutubeThrottlingDecrypter.decryptNParam(YoutubeThrottlingDecrypter.java:172)
        at org.schabi.newpipe.extractor.services.youtube.YoutubeThrottlingDecrypter.apply(YoutubeThrottlingDecrypter.java:92)
        at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.tryDecryption(YoutubeStreamExtractor.java:641)
        at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getAudioStreams(YoutubeStreamExtractor.java:574)
        	... 9 more

**Comment by sseodate** [comment]
Please release the update

**Comment by viyarda** [comment]
> 
Thanks, now I'm referencing 'com.github.TeamNewPipe:NewPipeExtractor:v0.22.1', no new version found.

**Comment by rajan6533** [comment]
Please release the update
