### ISSUE TITLE
YT Music: Playlist/Album extraction broken

### ISSUE THREAD

**Issue by litetex** [TeamNewPipe/NewPipeExtractor#908]
So after I fixed every test in the extractor (#882) I noticed that YT seems to have changed the music extraction which results in some errors:
![grafik](https://user-images.githubusercontent.com/40789489/186188742-9e3ea018-0284-47cc-99cc-b78f24524a9b.png)
```
java.lang.AssertionError: Next page have errors
  * Could not get url
  * Could not get url
  * Could not get url
  * Could not get url 
	at org.schabi.newpipe.extractor.ExtractorAsserts.assertEmptyErrors(ExtractorAsserts.java:28)
	at org.schabi.newpipe.extractor.services.DefaultTests.defaultTestMoreItems(DefaultTests.java:128)
	at org.schabi.newpipe.extractor.services.DefaultListExtractorTest.testMoreRelatedItems(DefaultListExtractorTest.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	... (remove junit internal stack)
	at java.lang.Thread.run(Thread.java:750)
Caused by: org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get url
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeMusicSearchExtractor$3.getUrl(YoutubeMusicSearchExtractor.java:554)
	at org.schabi.newpipe.extractor.playlist.PlaylistInfoItemsCollector.extract(PlaylistInfoItemsCollector.java:17)
	at org.schabi.newpipe.extractor.MultiInfoItemsCollector.extract(MultiInfoItemsCollector.java:86)
	at org.schabi.newpipe.extractor.MultiInfoItemsCollector.extract(MultiInfoItemsCollector.java:48)
	at org.schabi.newpipe.extractor.InfoItemsCollector.commit(InfoItemsCollector.java:104)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeMusicSearchExtractor.collectMusicStreamsFrom(YoutubeMusicSearchExtractor.java:501)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeMusicSearchExtractor.getPage(YoutubeMusicSearchExtractor.java:275)
	at org.schabi.newpipe.extractor.services.DefaultTests.defaultTestMoreItems(DefaultTests.java:125)
	... 91 more
```

**Comment by litetex** [comment]
After having a quick look I think the following was changed:
* Sometimes I get a "black" screen because the playlist is not found?
![grafik](https://user-images.githubusercontent.com/40789489/186190183-e35db80d-edf4-4be0-9aba-56eaf4184792.png)
* The menu is different for some items:
![grafik](https://user-images.githubusercontent.com/40789489/186190931-61da1232-811c-4b9b-83d2-d39541006669.png)
* If you click a video it directs to a browse url which is then redirected to a playlist url
![grafik](https://user-images.githubusercontent.com/40789489/186191308-a3f80314-0080-4c94-9f92-af7fd15b6e09.png)

**Comment by leolxmy** [comment]
I also encountered a similar problem, I was able to extract the youtube music playback link, but the playback failed due to authentication issues.

**Comment by FireMasterK** [comment]
Can this be closed?

They both work in Piped (and the tests pass now):
https://piped.video/results?search_query=test&filter=music_albums
https://piped.video/results?search_query=test&filter=music_playlists
