### ISSUE TITLE
[BUG]  java.lang.NoSuchMethodError: No virtual method stream()Lj$/util/stream/Stream; 

### ISSUE THREAD

**Issue by ag2s20150909** [TeamNewPipe/NewPipeExtractor#932]
```
 java.lang.NoSuchMethodError: No virtual method stream()Lj$/util/stream/Stream; in class Lcom/grack/nanojson/JsonArray; or its super classes (declaration of 'com.grack.nanojson.JsonArray' appears in /data/app/~~l-mSpG-jM95XfP3PJesyGg==/xxx.xxx.xx-nQJXDoJbMT1VutAruYsUBA==/base.apk!classes25.dex)
        at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getStreamsFromStreamingDataKey(YoutubeStreamExtractor.java:1409)
        at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.lambda$getItags$14$org-schabi-newpipe-extractor-services-youtube-extractors-YoutubeStreamExtractor(YoutubeStreamExtractor.java:1273)
        at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor$$ExternalSyntheticLambda13.apply(Unknown Source:10)
        at j$.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
        at j$.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at j$.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at j$.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at j$.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at j$.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:132)
        at j$.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at j$.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:502)
        at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getItags(YoutubeStreamExtractor.java:1276)
        at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getAudioStreams(YoutubeStreamExtractor.java:642)
```

https://issuetracker.google.com/issues/248247546

**Comment by AudricV** [comment]
This isn't something related to NewPipe Extractor, but something related to the desugarging process when compiling Android apps. Use the workaround provided in the original issue of the duplicate you linked until it is fixed with a new version of the desugar Android plugin.
