### ISSUE TITLE
Could not get any stream. See error variable to get further details.

### ISSUE THREAD

**Issue by subhadiprudra** [TeamNewPipe/NewPipeExtractor#948]
Getting error on StreamInfo.getInfo(NewPipe.getService(0), youtubeLink);

and StackTrace look like this
org.schabi.newpipe.extractor.stream.StreamInfo$StreamExtractException: Could not get any stream. See error variable to get further details.
at org.schabi.newpipe.extractor.stream.StreamInfo.extractStreams(StreamInfo.java:209)
at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:82)
at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:74)

**Comment by AudricV** [comment]
Please precise what extractor version you are using (or the commit SHA1).

**Comment by AudricV** [comment]
Closing due to lack of author's response.
